# Review https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run?hl=es-419
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/todoapp-340315/todoappbackend:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/todoapp-340315/todoappbackend:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'todoappbackend', '--image', 'gcr.io/todoapp-340315/todoappbackend:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/todoapp-340315/todoappbackend:$COMMIT_SHA'